apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-app-config
  labels:
    app: hello-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: hello-app
data:
  DB_HOST: "my-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "postgres"