apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: hello-app-config
                  key: dbName
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hello-app-secret
                  key: dbUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-app-secret
                  key: dbPassword
