replicaCount: 1

image:
  repository: 039612884386.dkr.ecr.us-east-1.amazonaws.com/hello-app
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/.well-known/acme-challenge/.*)$ $1 break;
  hosts:
    - host: sergeabroyan.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sergeabroyan.com
      secretName: tls-secret
